CREATE TABLE collection_items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date     TIMESTAMP with time zone                NOT NULL,
    update_date     TIMESTAMP with time zone                NOT NULL,
    item_name       VARCHAR(255)                            NOT NULL,
    image_link      VARCHAR(255)                            NOT NULL,
    image_public_id VARCHAR(255)                            NOT NULL,
    collection_id   BIGINT,
    CONSTRAINT pk_collection_items PRIMARY KEY (id)
);

CREATE TABLE collections
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date     TIMESTAMP with time zone                NOT NULL,
    update_date     TIMESTAMP with time zone                NOT NULL,
    collection_name VARCHAR(255)                            NOT NULL,
    theme_id        BIGINT                                  NOT NULL,
    owner_id        BIGINT                                  NOT NULL,
    image_link      VARCHAR(255)                            NOT NULL,
    image_public_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_collections PRIMARY KEY (id)
);

CREATE TABLE item_comments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date     TIMESTAMP with time zone                NOT NULL,
    update_date     TIMESTAMP with time zone                NOT NULL,
    comment_content VARCHAR(255)                            NOT NULL,
    author_id       BIGINT                                  NOT NULL,
    item_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_item_comments PRIMARY KEY (id)
);

CREATE TABLE item_fields
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date  TIMESTAMP with time zone                NOT NULL,
    update_date  TIMESTAMP with time zone                NOT NULL,
    field_name   VARCHAR(255)                            NOT NULL,
    field_value  VARCHAR(255)                            NOT NULL,
    content_type VARCHAR(255)                            NOT NULL,
    item_id      BIGINT,
    CONSTRAINT pk_item_fields PRIMARY KEY (id)
);

CREATE TABLE item_tags
(
    items_id BIGINT NOT NULL,
    tags_id  BIGINT NOT NULL,
    CONSTRAINT pk_item_tags PRIMARY KEY (items_id, tags_id)
);

CREATE TABLE likes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date TIMESTAMP with time zone                NOT NULL,
    update_date TIMESTAMP with time zone                NOT NULL,
    author_id   BIGINT                                  NOT NULL,
    item_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date TIMESTAMP with time zone                NOT NULL,
    update_date TIMESTAMP with time zone                NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date TIMESTAMP with time zone                NOT NULL,
    update_date TIMESTAMP with time zone                NOT NULL,
    role_name   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE tags
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date TIMESTAMP with time zone                NOT NULL,
    update_date TIMESTAMP with time zone                NOT NULL,
    tag_name    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

CREATE TABLE themes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date TIMESTAMP with time zone                NOT NULL,
    update_date TIMESTAMP with time zone                NOT NULL,
    theme_name  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_themes PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date TIMESTAMP with time zone                NOT NULL,
    update_date TIMESTAMP with time zone                NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    secret      VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    last_login  TIMESTAMP with time zone                NOT NULL,
    active      BOOLEAN                                 NOT NULL,
    blocked     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE collection_items
    ADD CONSTRAINT uc_collection_items_item_name UNIQUE (item_name);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_role_name UNIQUE (role_name);

ALTER TABLE tags
    ADD CONSTRAINT uc_tags_tag_name UNIQUE (tag_name);

ALTER TABLE themes
    ADD CONSTRAINT uc_themes_theme_name UNIQUE (theme_name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE collections
    ADD CONSTRAINT FK_COLLECTIONS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE collections
    ADD CONSTRAINT FK_COLLECTIONS_ON_THEME FOREIGN KEY (theme_id) REFERENCES themes (id);

ALTER TABLE collection_items
    ADD CONSTRAINT FK_COLLECTION_ITEMS_ON_COLLECTION FOREIGN KEY (collection_id) REFERENCES collections (id) ON DELETE CASCADE;

ALTER TABLE item_comments
    ADD CONSTRAINT FK_ITEM_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE item_comments
    ADD CONSTRAINT FK_ITEM_COMMENTS_ON_ITEM FOREIGN KEY (item_id) REFERENCES collection_items (id) ON DELETE CASCADE;

ALTER TABLE item_fields
    ADD CONSTRAINT FK_ITEM_FIELDS_ON_ITEM FOREIGN KEY (item_id) REFERENCES collection_items (id) ON DELETE CASCADE;

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_ITEM FOREIGN KEY (item_id) REFERENCES collection_items (id) ON DELETE CASCADE;

ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESH_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE item_tags
    ADD CONSTRAINT fk_item_tags_on_collection_item FOREIGN KEY (items_id) REFERENCES collection_items (id);

ALTER TABLE item_tags
    ADD CONSTRAINT fk_item_tags_on_tag FOREIGN KEY (tags_id) REFERENCES tags (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);

INSERT INTO roles (create_date, update_date, role_name)
VALUES (NOW(), NOW(), 'ROLE_USER'),
       (NOW(), NOW(), 'ROLE_ADMIN'),
       (NOW(), NOW(), 'ROLE_ROOT')
ON CONFLICT DO NOTHING;

INSERT INTO users (create_date, update_date, username, secret, email, last_login, active, blocked)
VALUES (NOW(), NOW(), 'root', '$2a$12$4rC4NtEhJ38Q1Iu9CSTq/e66X/bI2JWD5CQtuWUkNPIyPTOFpjpM2',
        'root@guard.gd', NOW(), false, false)
ON CONFLICT DO NOTHING;

INSERT INTO user_roles (role_id, user_id)
VALUES (3, 1)
ON CONFLICT DO NOTHING;